//Card Type
export const SHOW_SCREENSHOTS = 'SHOW_SCREENSHOTS';
export const SHOW_GAMES = 'SHOW_GAMES';
export const SHOW_STREAMS = 'SHOW_STREAMS';

//Carousel Type
export const CAROUSEL_DASHBOARD = 'CAROUSEL_DASHBOARD';
export const CAROUSEL_SCREENSHOT = 'CAROUSEL_SCREENSHOT';
