export const SHOW_LEFT_SIDEBAR = 'SHOW_LEFT_SIDEBAR';
export const SHOW_RIGHT_SIDEBAR = 'SHOW_RIGHT_SIDEBAR';

/* Context Types */

export const SHOW_LEFT_SIDEBAR_FRIENDS = 'SHOW_LEFT_SIDEBAR_FRIENDS';
export const SHOW_LEFT_SIDEBAR_CHANNELLIST = 'SHOW_LEFT_SIDEBAR_CHANNELLIST';
export const SHOW_RIGHT_SIDEBAR_GAMES = 'SHOW_RIGHT_SIDEBAR_GAMES';
export const SHOW_RIGHT_SIDEBAR_USERLIST = 'SHOW_RIGHT_SIDEBAR_USERLIST';
export const SHOW_RIGHT_SIDEBAR_STREAMCHAT = 'SHOW_RIGHT_SIDEBAR_STREAMCHAT';
