export const LOAD_CURRENT_SERVER = "SET_CURRENT_SERVER";
export const LOAD_USER_JOINED_SERVERS = "LOAD_USER_JOINED_SERVERS";
export const LOAD_SERVER_USERLIST = "LOAD_SERVER_USERLIST";
export const LOAD_SERVER_CHANNELLIST = "LOAD_SERVER_CHANNELLIST";
export const LOAD_CURRENT_CHANNEL = "LOAD_CURRENT_CHANNEL";