export const SET_SOCKET = "SET_SOCKET";
export const JOIN_VOICE_CHAT = "JOIN_VOICE_CHAT";
export const UPDATE_USERLIST = "UPDATE_USERLIST";
export const UPDATE_RTC_PEER_CONNECTION = "UPDATE_RTC_PEER_CONNECTION";
export const SET_REMOTE_STREAM = "SET_REMOTE_STREAM";