export const CAPTURE_FRIENDS = 'CAPTURE_FRIENDS';
export const CAPTURE_PROFILES = 'CAPTURE_PROFILES';
export const LOAD_CURRENT_PROFILE = 'LOAD_CURRENT_PROFILE';
export const CAPTURE_GAMES = 'CAPTURE_GAMES';
export const SET_OWNED_CURRENT_GAME = 'SET_OWNED_CURRENT_GAME';
